apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/uncle5withsword/udagram-api-user:v3
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1024Mi"
            cpu: 500m
          requests:
            memory: "100Mi"
            cpu: 200m
